### PR TITLE
Update repo path from mholt/caddy to caddyserver/caddy

### PR DESCRIPTION
**Pull request by EricNilsson**

### CODE REVIEW

**Comment by abiosoft** [comment]
Thanks, but I'm working on this already. The change broke all plugins that haven't updated to match the new modules import path. I'm trying to see if I can find a middle ground before pushing it.

**Comment by damwiw** [comment]
Hi,
Was on it today as well. Looks like this change is not enough. You need to update caddyplug as well.
When there's no plugin, this change is enough with versions 1.0.1 and 1.0.0.
Thanks for your nice work.

**Comment by damwiw** [comment]
There're other issues if some users want to use older version, such as 0.11.5.
legacy function within builder.sh script will fail. This is due to main.go source file that keep on using mholt path:
```
package main

import "github.com/mholt/caddy/caddy/caddymain"

```

So older versions require to use or to load the former github paths.

**Comment by abiosoft** [comment]
@damwiw yeah, I'm aware of both scenarios.

**Comment by EricNilsson** [comment]
@abiosoft Yes, I figured that it wasn't a complete solution. I did it partly to get your attention on the matter and partly as an attempt at a solution :) 

Is there some way we could pass each plugin through the search/replace that matt suggests here? https://github.com/BTBurke/caddy-jwt/issues/51#issue-463449651

**Comment by abiosoft** [comment]
The fix is pushed to master. You'd have to wait a bit for docker hub to finish building the images. And I'd push tag releases afterwards.

With regards to `abiosoft/caddy:builder`, it's too hacky to make it support older Caddy versions. So you need to build with `>=v1.0.1`. All plugins should now work (including those not yet updated to the new import path).

**Comment by EricNilsson** [comment]
Great! Thanks for your work.

**Comment by damwiw** [comment]
Thanks! Have a good day.

**Pull request closed without merging**
