### PR TITLE
Temporary fix: check import_package before writing

### PR DESCRIPTION
**Pull request by ghost**
This pull request tries to fix `invalid import path: ""` (related issues: #222 #220 )

I've noticed this behavior recently in my build pipline and tried `caddyplug package` alone: it fails for the first one or two times and works all the following try.

I've checked the source code, but found nothing could result this behavior, so I decide to make this temporary fix, hope this will work for everyone else.

### CODE REVIEW

**Comment by gabegundy** [comment]
Just FYI, this didn't work for me. Fails in the same way that master does.

```docker build --build-arg \
    plugins="git,cors,realip,expires,cache,googlecloud" \
    github.com/abiosoft/caddy-docker.git#pull/223/head

...

can't load package: package caddy: 
cors.go:2:10: invalid import path: ""
error at 'building caddy'
The command '/bin/sh -c VERSION=${version} PLUGINS=${plugins} ENABLE_TELEMETRY=${enable_telemetry} /bin/sh /usr/bin/builder.sh' returned a non-zero code: 1
```

**Comment by jeffreystoke** [comment]
@gabegundy you have to rebuild `abiosoft/caddy:builder` first, the `builder.sh` is bundled inside it.

**Comment by jffin** [comment]
Hello, can you make an advice please
is there a way to use your pull in DockerFile?

# process wrapper
RUN go get -v github.com/abiosoft/parent

As i understand builder.sh is downloading here
but how can be downloaded your pull instead?

**Comment by jeffreystoke** [comment]
@jffin just replace `builder.sh` for the `abiosoft/caddy:builder`, if you are using the [default dockerfile in this repo](https://github.com/abiosoft/caddy-docker/blob/master/Dockerfile)

```dockerfile
#
# Builder
#
FROM abiosoft/caddy:builder

# add this line before you run `/bin/sh /usr/bin/builder.sh`
ADD https://raw.githubusercontent.com/jeffreystoke/caddy-docker/master/builder/builder.sh /usr/bin/builder.sh

# ... 

#
# Final stage
#
FROM alpine:3.10

# ...
```

**Comment by jffin** [comment]
it works
thanks a lot

**Comment by jeffreystoke** [comment]
@tobiasmuehl that could happen since there is no limit to the retry, can you make sure your plugin is properly annotated with package here: https://github.com/caddyserver/caddy/blob/96579b97f687c95aeb85f09029d48122d84c668e/caddyhttp/httpserver/plugin.go#L626

Note: change the file version to match yours.

**Comment by tobiasmuehl** [comment]
@jeffreystoke That explains it, the redis plugin is missing from the list. Using the build service from caddyserver.com for now but would prefer to self-build.

**Comment by tobiasmuehl** [comment]
Redis is a clustering plugin so it probably belongs somewhere else, not in `directives`. 

    // directives is the list of all directives known to exist for the
    // http server type, including non-standard (3rd-party) directives.

**Comment by gabegundy** [comment]
@tobiasmuehl I see that now. Thanks. I reworked the build to be muti-stage (seems cleaner anyway) and it works great. Thanks.

**Comment by SimJoSt** [comment]
Unfortunately it doesn't seem to work anymore. I just tried it with the Dockerfile snippet and didn't have any luck.

**Comment by sparampalli** [comment]
> @tobiasmuehl that could happen since there is no limit to the retry, can you make sure your plugin is properly annotated with package here: https://github.com/caddyserver/caddy/blob/96579b97f687c95aeb85f09029d48122d84c668e/caddyhttp/httpserver/plugin.go#L626
> 
> Note: change the file version to match yours.



> Redis is a clustering plugin so it probably belongs somewhere else, not in `directives`.
> 
> ```
> // directives is the list of all directives known to exist for the
> // http server type, including non-standard (3rd-party) directives.
> ```

Hi,

I am also running into the same issue. Can you please elaborate on the steps that you followed?

**Comment by aguglie** [comment]
Anyone managed to solve?
@jeffreystoke 's fix seems not to be working anymore:

```
docker build --build-arg \
    plugins=git \
    github.com/jeffreystoke/caddy-docker.git
```

Got same error:

```
can't load package: package caddy: 
git.go:2:10: invalid import path: ""
error at 'building caddy'
The command '/bin/sh -c VERSION=${version} PLUGINS=${plugins} ENABLE_TELEMETRY=${enable_telemetry} /bin/sh /usr/bin/builder.sh' returned a non-zero code: 1
```

**Comment by tobiasmuehl** [comment]
@sparampalli I'm not self building, using the commercial installer provided. Here's my dockerfile:

```dockerfile
FROM alpine

RUN apk update && apk add bash curl
RUN curl https://getcaddy.com | bash -s personal redis
ADD Caddyfile /etc/Caddyfile
ENTRYPOINT ["caddy"]
CMD ["--conf", "/etc/Caddyfile", "--agree=true"]
```

**Comment by oslah212** [comment]
Someone managed to solve this problem.
I can't build.
I've tried using the script above but it freezes when loading the plugins.

It only works with the "cloudflare" plugin, but I need to include other plugins.

Does anyone find a solution to this error?

**Comment by aguglie** [comment]
@oslah212 i found no way. I solved it bundling the pre-compiled Caddy executable in the docker container. Dirty fix but needed.

**Comment by oslah212** [comment]
hi @Guglio95 . How can I solve it this way? My goal is to use it with some additional plugins.

**Comment by ghost** [comment]
When I want to use plugin namesilo, i build caddy in this way. Hope it would help.
```
#
FROM abiosoft/caddy:builder as builder1

ARG version="1.0.3"
ARG plugins="namesilo"

# process wrapper
RUN go get -v github.com/abiosoft/parent

RUN VERSION=${version} PLUGINS=${plugins} ENABLE_TELEMETRY=false /bin/sh /usr/bin/builder.sh
```

**Comment by tobiasmuehl** [comment]
Please note that this issue was created for Caddy 1, not Caddy 2.

**Comment by aguglie** [comment]
@oslah212 you should get the [Caddy v1 binary](https://github.com/caddyserver/caddy/releases/tag/v1.0.4), or compile it by yourself if you need additional plugins. 
Then you should create a docker container bundling in it the compiled executable. 
This is a bad trick, but I needed to get it working; then I migrated to Caddy v2 :smile: 

```
FROM alpine:3.10

ADD caddy /usr/bin/caddy
COPY Caddyfile /etc/Caddyfile

VOLUME /root/.caddy
VOLUME /var/log

ENTRYPOINT ["/bin/sh"]
CMD ["/usr/bin/caddy", "--conf", "/etc/Caddyfile", "--log", "stdout", "--agree=false"]
```

**Pull request closed without merging**
