### PR TITLE
Run as non-root

### LINKED ISSUE #11: USER instruction for building secure Docker images
Should there be a USER instruction included in the Dockerfile for added security as described in https://www.youtube.com/watch?v=LmUw2H6JgJo?

### PR DESCRIPTION
**Pull request by MatthewVance**
Closes #11

### CODE REVIEW

**Comment by larskluge** [comment]
Oh boy, overwriting the public docker tag `0.9.1` with this was not cool. Pulled our cluster down since we use caddy (this image) to proxy to a private docker registry.. Would be cool to avoid overwriting public tags in the future when behavior like user change within the image happens.. 

However, great project after all!

**Comment by larskluge** [comment]
In case somebody else needs the old image, it's available at `babl/caddy:0.9.1`, built from this commit: https://github.com/abiosoft/caddy-docker/commit/d778fdde0b91aad81e49014c4a4e63e0ef81898a

**Comment by abiosoft** [comment]
@larskluge I'm really sorry for that. Lesson learnt.

**Comment by larskluge** [comment]
No worries, thanks @abiosoft !

**Pull request merged**
