### PR TITLE
Added Cloudflare + php7-bcmath support

### PR DESCRIPTION
**Pull request by adriel**
Built and tested to be working.

### CODE REVIEW

**Comment by adriel** [comment]
Would you also be open to adding the Cloudflare plugin? As without it, you can't really use Caddy when your domains are also behind Cloudflare.

**Comment by abiosoft** [comment]
The challenge will bundling other plugins is primarily maintenance. I prefer to include plugins I can respond to its requests.

**Comment by adriel** [comment]
All right, are you able to just approve the bcmath addition then? Or do I need to create a new PL?

**Comment by abiosoft** [comment]
You can create an additional commit to revert the cloudfare addition and I'll merge it in.

Thanks.

**Comment by abiosoft** [comment]
By the way, I am open to ideas to make plugin inclusion dynamic if possible. 

As a workaround, you can base your image off this as many other people have done.

**Comment by adriel** [comment]
Sweet, removed Cloudflare.

I've relatively new to Docker but from what I can see it looks like tags are the only way to include different plugins and keep them out of the main build... not really ideal.

And yeah thanks, I've already forked this project and running it locally with CloudFlare. 

Would you be ok if I published it on hub.docker? (giving you credit of course)

**Comment by abiosoft** [comment]
Not a problem.

**Pull request merged**
